# Generated by Django 5.1.1 on 2025-10-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_mode', models.CharField(choices=[('PLAINTEXT', 'Plaintext'), ('WEAK_XOR', 'Weak XOR'), ('END_TO_END', 'End-to-End Encrypted'), ('END_TO_END_STEGO', 'End-to-End Encrypted + Steganography')], default='PLAINTEXT', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encryption setting',
                'verbose_name_plural': 'Encryption settings',
            },
        ),
    ]
