# Generated by Django 5.1.1 on 2025-10-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encryption_mode',
            field=models.CharField(default='plaintext', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='plaintext_preview',
            field=models.TextField(blank=True, default=''),
        ),
    ]
