# Generated by Django 5.1.1 on 2025-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ciphertext',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='encryption_mode',
            field=models.CharField(default='plaintext', max_length=64),
        ),
    ]
