# Generated by Django 5.1.1 on 2025-10-12 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_encryption_mode_message_plaintext_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='encryption_mode',
        ),
        migrations.RemoveField(
            model_name='message',
            name='plaintext_preview',
        ),
    ]
