# Generated by Django 5.1.1 on 2025-10-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_remove_message_encryption_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='encryption_type',
            field=models.CharField(choices=[('PLAINTEXT', 'Plaintext'), ('WEAK_XOR', 'Weak XOR'), ('END_TO_END', 'End-to-End Encrypted'), ('END_TO_END_STEGO', 'End-to-End Encrypted + Steganography')], default='PLAINTEXT', max_length=32),
        ),
    ]
